# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import pytest
import enum as module_0
import umlrelation as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 0
    module_0.unique(int_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    list_0 = []
    module_0.unique(list_0)


def test_case_2():
    rel_type_0 = module_1.RelType.INHERITANCE
    str_0 = "hg1ZA"
    none_type_0 = None
    str_1 = "8$g,_\rOp`1MhzgKl\ni<"
    str_2 = "255()%2\x0c"
    uml_relation_0 = module_1.UmlRelation(str_1, str_2, str_1)
    var_0 = uml_relation_0.__eq__(rel_type_0)
    var_1 = uml_relation_0.__eq__(str_0)
    var_2 = uml_relation_0.__repr__()
    rel_type_1 = module_1.RelType.COMPOSITION
    var_3 = var_2.__eq__(rel_type_1)
    uml_relation_1 = module_1.UmlRelation(str_0, none_type_0, rel_type_0)
    var_4 = uml_relation_1.__repr__()
    assert (
        var_4
        == "UmlRelation(source_fqn='hg1ZA', target_fqn=None, type=<RelType.INHERITANCE: '<|'>)"
    )
    var_5 = var_4.__repr__()
    assert (
        var_5
        == "\"UmlRelation(source_fqn='hg1ZA', target_fqn=None, type=<RelType.INHERITANCE: '<|'>)\""
    )
    var_6 = rel_type_1.__repr__()
    assert var_6 == "<RelType.COMPOSITION: '*'>"
    var_7 = var_6.__repr__()
    assert var_7 == "\"<RelType.COMPOSITION: '*'>\""
    var_8 = var_5.__eq__(uml_relation_0)
    var_9 = var_8.__eq__(var_0)

def test_case_3():
    uml_relation_0 = module_1.UmlRelation("source_fqn_3", "target_fqn_3", module_1.RelType.COMPOSITION)
    assert uml_relation_0.__repr__() == "UmlRelation(source_fqn='source_fqn_3', target_fqn='target_fqn_3', type=<RelType.COMPOSITION: '*'>)"

def test_case_4():
    uml_relation_0 = module_1.UmlRelation("source_fqn_4", "target_fqn_4", module_1.RelType.INHERITANCE)
    assert uml_relation_0.__repr__() == "UmlRelation(source_fqn='source_fqn_4', target_fqn='target_fqn_4', type=<RelType.INHERITANCE: '<|'>)"

def test_case_5():
    uml_relation_0 = module_1.UmlRelation("source_fqn_5", "target_fqn_5", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_5", "target_fqn_5", module_1.RelType.COMPOSITION)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_6():
    uml_relation_0 = module_1.UmlRelation("source_fqn_6", "target_fqn_6", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_6", "target_fqn_6", module_1.RelType.INHERITANCE)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_7():
    uml_relation_0 = module_1.UmlRelation("source_fqn_7", "target_fqn_7", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_7", "target_fqn_8", module_1.RelType.COMPOSITION)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_8():
    uml_relation_0 = module_1.UmlRelation("source_fqn_8", "target_fqn_8", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_9", "target_fqn_8", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_9():
    uml_relation_0 = module_1.UmlRelation("source_fqn_9", "target_fqn_9", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_9", "target_fqn_9", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_10():
    uml_relation_0 = module_1.UmlRelation("source_fqn_10", "target_fqn_10", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_10", "target_fqn_10", module_1.RelType.COMPOSITION)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_11():
    uml_relation_0 = module_1.UmlRelation("source_fqn_11", "target_fqn_11", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_11", "target_fqn_11", module_1.RelType.COMPOSITION)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_12():
    uml_relation_0 = module_1.UmlRelation("source_fqn_12", "target_fqn_12", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_12", "target_fqn_12", module_1.RelType.INHERITANCE)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_13():
    uml_relation_0 = module_1.UmlRelation("source_fqn_13", "target_fqn_13", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_13", "target_fqn_14", module_1.RelType.COMPOSITION)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_14():
    uml_relation_0 = module_1.UmlRelation("source_fqn_14", "target_fqn_14", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_15", "target_fqn_14", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_15():
    uml_relation_0 = module_1.UmlRelation("source_fqn_15", "target_fqn_15", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_15", "target_fqn_15", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_16():
    uml_relation_0 = module_1.UmlRelation("source_fqn_16", "target_fqn_16", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_16", "target_fqn_16", module_1.RelType.COMPOSITION)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_17():
    uml_relation_0 = module_1.UmlRelation("source_fqn_17", "target_fqn_17", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_17", "target_fqn_17", module_1.RelType.INHERITANCE)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_18():
    uml_relation_0 = module_1.UmlRelation("source_fqn_18", "target_fqn_18", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_19", "target_fqn_19", module_1.RelType.COMPOSITION)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_19():
    uml_relation_0 = module_1.UmlRelation("source_fqn_19", "target_fqn_19", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_20", "target_fqn_20", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_20():
    uml_relation_0 = module_1.UmlRelation("source_fqn_20", "target_fqn_20", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_20", "target_fqn_21", module_1.RelType.COMPOSITION)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_21():
    uml_relation_0 = module_1.UmlRelation("source_fqn_21", "target_fqn_21", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_22", "target_fqn_21", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_22():
    uml_relation_0 = module_1.UmlRelation("source_fqn_22", "target_fqn_22", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_22", "target_fqn_22", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_23():
    uml_relation_0 = module_1.UmlRelation("source_fqn_23", "target_fqn_23", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_23", "target_fqn_23", module_1.RelType.COMPOSITION)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_24():
    uml_relation_0 = module_1.UmlRelation("source_fqn_24", "target_fqn_24", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_24", "target_fqn_24", module_1.RelType.INHERITANCE)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_25():
    uml_relation_0 = module_1.UmlRelation("source_fqn_25", "target_fqn_25", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_25", "target_fqn_25", module_1.RelType.COMPOSITION)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_26():
    uml_relation_0 = module_1.UmlRelation("source_fqn_26", "target_fqn_26", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_26", "target_fqn_26", module_1.RelType.INHERITANCE)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_27():
    uml_relation_0 = module_1.UmlRelation("source_fqn_27", "target_fqn_27", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_27", "target_fqn_27", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_28():
    uml_relation_0 = module_1.UmlRelation("source_fqn_25", "target_fqn_28", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_98", "target_fqn_98", module_1.RelType.COMPOSITION)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_29():
    uml_relation_0 = module_1.UmlRelation("source_fqn_29", "target_fqn_29", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_30", "target_fqn_30", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_30():
    uml_relation_0 = module_1.UmlRelation("source_fqn_30", "target_fqn_30", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_30", "target_fqn_30", module_1.RelType.COMPOSITION)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_31():
    uml_relation_0 = module_1.UmlRelation("source_fqn_31", "target_fqn_31", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_31", "target_fqn_31", module_1.RelType.INHERITANCE)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_32():
    uml_relation_0 = module_1.UmlRelation("source_fqn_32", "target_fqn_32", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_32", "target_fqn_32", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_33():
    uml_relation_0 = module_1.UmlRelation("source_fqn_33", "target_fqn_33", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_33", "target_fqn_33", module_1.RelType.COMPOSITION)
    assert not uml_relation_0.__eq__(uml_relation_1)
    
def test_case_34():
    uml_relation_0 = module_1.UmlRelation("source_fqn_33", "target_fqn_34", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_30", "target_fqn_30", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_35():
    uml_relation_0 = module_1.UmlRelation("source_fqn_35", "target_fqn_35", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_35", "target_fqn_35", module_1.RelType.COMPOSITION)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_36():
    uml_relation_0 = module_1.UmlRelation("source_fqn_36", "target_fqn_36", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_36", "target_fqn_36", module_1.RelType.INHERITANCE)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_37():
    uml_relation_0 = module_1.UmlRelation("source_fqn_37", "target_fqn_37", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_37", "target_fqn_37", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_38():
    uml_relation_0 = module_1.UmlRelation("source_fqn_38", "target_fqn_38", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_38", "target_fqn_38", module_1.RelType.COMPOSITION)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_39():
    uml_relation_0 = module_1.UmlRelation("source_fqn_98", "target_fqn_29", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_30", "target_fqn_30", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_40():
    uml_relation_0 = module_1.UmlRelation("source_fqn_44", "target_fqn_44", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_44", "target_fqn_44", module_1.RelType.COMPOSITION)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_41():
    uml_relation_0 = module_1.UmlRelation("source_fqn_41", "target_fqn_41", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_41", "target_fqn_41", module_1.RelType.INHERITANCE)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_42():
    uml_relation_0 = module_1.UmlRelation("source_fqn_32", "target_fqn_32", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_32", "target_fqn_32", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_43():
    uml_relation_0 = module_1.UmlRelation("source_fqn_43", "target_fqn_43", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_43", "target_fqn_43", module_1.RelType.COMPOSITION)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_44():
    uml_relation_0 = module_1.UmlRelation("source_fqn_47", "target_fqn_47", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_48", "target_fqn_48", module_1.RelType.COMPOSITION)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_45():
    uml_relation_0 = module_1.UmlRelation("source_fqn_29", "target_fqn_29", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_30", "target_fqn_30", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_46():
    uml_relation_0 = module_1.UmlRelation("source_fqn_30", "target_fqn_30", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_30", "target_fqn_30", module_1.RelType.COMPOSITION)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_47():
    uml_relation_0 = module_1.UmlRelation("source_fqn_31", "target_fqn_31", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_31", "target_fqn_31", module_1.RelType.INHERITANCE)
    assert uml_relation_0.__eq__(uml_relation_1)

def test_case_48():
    uml_relation_0 = module_1.UmlRelation("source_fqn_32", "target_fqn_32", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_32", "target_fqn_32", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_48():
    uml_relation_0 = module_1.UmlRelation("source_fqn_48", "target_fqn_48", module_1.RelType.COMPOSITION)
    uml_relation_1 = module_1.UmlRelation("source_fqn_49", "target_fqn_49", module_1.RelType.COMPOSITION)
    assert not uml_relation_0.__eq__(uml_relation_1)

def test_case_49():
    uml_relation_0 = module_1.UmlRelation("source_fqn_49", "target_fqn_49", module_1.RelType.INHERITANCE)
    uml_relation_1 = module_1.UmlRelation("source_fqn_50", "target_fqn_50", module_1.RelType.INHERITANCE)
    assert not uml_relation_0.__eq__(uml_relation_1)
