# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import pytest
import cli as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    module_0.run()

