# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import enum as module_0
import inspectenum as module_1


def test_case_0():
    type_0 = module_0.Enum
    module_1.inspect_enum_type(type_0, type_0, type_0)
