# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import py2puml.domain.umlenum as module_0
import puml as module_1
import py2puml.domain.umlitem as module_2


def test_case_0():
    str_0 = 'sAie"_+IJw\rq,SB+'
    none_type_0 = None
    str_1 = "\x0b`v6="
    none_type_1 = None
    uml_enum_0 = module_0.UmlEnum(str_0, str_1, none_type_1)
    var_0 = uml_enum_0.__eq__(str_0)
    var_1 = var_0.__repr__()
    var_2 = var_1.__repr__()
    var_3 = var_2.__repr__()
    var_4 = var_3.__eq__(none_type_0)
    var_5 = var_4.__repr__()
    uml_enum_1 = module_0.UmlEnum(none_type_0, var_1, var_4)
    list_0 = [var_5, uml_enum_1, var_3]
    iterable_0 = module_1.to_puml_content(str_0, list_0, none_type_1)
    assert module_1.PUML_FILE_START == "@startuml {diagram_name}\n"
    assert module_1.PUML_FILE_FOOTER == "footer Generated by //py2puml//\n"
    assert module_1.PUML_FILE_END == "@enduml\n"
    assert module_1.PUML_ITEM_START_TPL == "{item_type} {item_fqn} {{\n"
    assert module_1.PUML_ATTR_TPL == "  {attr_name}: {attr_type}{staticity}\n"
    assert module_1.PUML_ITEM_END == "}\n"
    assert module_1.PUML_RELATION_TPL == "{source_fqn} {rel_type}-- {target_fqn}\n"
    assert module_1.FEATURE_STATIC == " {static}"
    assert module_1.FEATURE_INSTANCE == ""
    none_type_2 = None
    list_1 = []
    uml_enum_2 = module_0.UmlEnum(str_0, none_type_2, list_1)
    list_2 = [uml_enum_2]
    var_6 = uml_enum_2.__repr__()
    list_3 = [var_6, var_6, var_6]
    iterable_1 = module_1.to_puml_content(str_0, list_2, list_3)
    uml_item_0 = module_2.UmlItem(str_0, str_0)
    var_7 = uml_item_0.__eq__(str_0)
    list_4 = [var_7, var_7, var_7, var_7]
    iterable_2 = module_1.to_puml_content(str_0, str_0, list_4)
