# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import dataclasses as module_0
import umlclass as module_1


def test_case_0():
    float_0 = -1256.0
    module_0.dataclass(float_0, kw_only=float_0)


def test_case_1():
    str_0 = 'kH6o$qH\ry2d"\x0b\rC5v-'
    str_1 = "Vv1-T"
    str_2 = "W$x\"zla;/\x0c\nB'J\\K"
    uml_attribute_0 = module_1.UmlAttribute(str_1, str_2, str_2)
    var_0 = uml_attribute_0.__eq__(str_0)
    uml_attribute_1 = module_1.UmlAttribute(str_0, var_0, str_1)
    float_0 = 1321.0
    str_3 = "r"
    none_type_0 = None
    uml_attribute_2 = module_1.UmlAttribute(str_3, str_3, none_type_0)
    var_1 = uml_attribute_2.__repr__()
    var_2 = var_1.__eq__(var_1)
    var_3 = var_1.__eq__(float_0)


def test_case_2():
    var_0 = module_0.dataclass()
    var_1 = var_0.__eq__(var_0)
    var_2 = var_0.__repr__()
    tuple_0 = (var_0, var_0)
    list_0 = [var_0]
    uml_class_0 = module_1.UmlClass(var_0, tuple_0, list_0)
    uml_class_1 = module_1.UmlClass(tuple_0, var_0, var_0)
    var_3 = var_0.__repr__()
    var_4 = uml_class_1.__repr__()
    var_5 = uml_class_1.__repr__()
    var_6 = var_2.__eq__(var_5)
    str_0 = "A]cCX4'4T!b"
    uml_class_2 = module_1.UmlClass(str_0, str_0, str_0)
    var_7 = var_2.__eq__(uml_class_1)
    var_8 = uml_class_2.__repr__()
    var_9 = list_0.__eq__(uml_class_0)
